sudo: required
services: docker
language: generic

env:
  matrix:
    - IMAGE=archlinux
    - IMAGE=archlinux-webengine
    - IMAGE=archlinux-webengine-unstable
    - IMAGE=debian-jessie
    - IMAGE=ubuntu-xenial

script:
  - travis_retry docker build -t "qutebrowser/travis:$IMAGE" "$IMAGE"
  - 'if [[ $TRAVIS_PULL_REQUEST == false ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi'
  - 'if [[ $TRAVIS_PULL_REQUEST == false ]]; then docker push "qutebrowser/travis:$IMAGE"; fi'

notifications:
  irc:
    channels:
      - "chat.freenode.net#qutebrowser-dev"
    on_success: always
    on_failure: always
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "%{compare_url} - %{build_url}"
