sudo: required
services: docker
language: generic

env:
  matrix:
    - IMAGE=archlinux
    - IMAGE=debian-jessie
    - IMAGE=ubuntu-xenial

script:
  - docker build -t "qutebrowser/travis:$IMAGE" "$IMAGE"
  - '[[ $TRAVIS_PULL_REQUEST == false ]] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"'
  - '[[ $TRAVIS_PULL_REQUEST == false ]] && docker push "qutebrowser/travis:$IMAGE"'

notifications:
  irc:
    channels:
      - "chat.freenode.net#qutebrowser-dev"
    on_success: always
    on_failure: always
    skip_join: true
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "%{compare_url} - %{build_url}"
